### PR TITLE
fix compilation error by removing unused parts of termstylist

### PR DESCRIPTION
**Pull request by Connorppeach**

### CODE REVIEW

**Comment by sylv256** [comment]
I use termstylist for styling the console output. I'd rather keep it. If you could create an issue on the termstylist repository with your error, that would be fine.

**Comment by Connorppeach** [comment]
The pr keeps term stylist, just removes non-compiling parts and output of the program is unchanged.  Also term stylist has not seen a commit in 3 years

**Comment by sylv256** [comment]
Could you send a copy of the error along with what compiler you're using? I use clang 17.

**Comment by Connorppeach** [comment]
im using gcc 13.2.1

**Comment by Connorppeach** [comment]
[error.txt](https://github.com/TerraxGames/unnominable/files/14817705/error.txt)

**Comment by sylv256** [comment]
I'll get around to fixing this sometime soon. For now, we use clang.

**Pull request closed without merging**
